<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [

            // -------------------------
            // EUROPE
            // -------------------------
            [
                'iso_3166_2' => 'AL',
                'iso_3166_3' => 'ALB',
                'name_en' => 'Albania',
                'name_de' => 'Albanien',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'ALL',
                'phone_code' => '+355',
            ],
            [
                'iso_3166_2' => 'AD',
                'iso_3166_3' => 'AND',
                'name_en' => 'Andorra',
                'name_de' => 'Andorra',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+376',
            ],
            [
                'iso_3166_2' => 'AT',
                'iso_3166_3' => 'AUT',
                'name_en' => 'Austria',
                'name_de' => 'Österreich',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+43',
            ],
            [
                'iso_3166_2' => 'BY',
                'iso_3166_3' => 'BLR',
                'name_en' => 'Belarus',
                'name_de' => 'Belarus',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'currency_code' => 'BYN',
                'phone_code' => '+375',
            ],
            [
                'iso_3166_2' => 'BE',
                'iso_3166_3' => 'BEL',
                'name_en' => 'Belgium',
                'name_de' => 'Belgien',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+32',
            ],
            [
                'iso_3166_2' => 'BA',
                'iso_3166_3' => 'BIH',
                'name_en' => 'Bosnia and Herzegovina',
                'name_de' => 'Bosnien und Herzegowina',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'BAM',
                'phone_code' => '+387',
            ],
            [
                'iso_3166_2' => 'BG',
                'iso_3166_3' => 'BGR',
                'name_en' => 'Bulgaria',
                'name_de' => 'Bulgarien',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'currency_code' => 'BGN',
                'phone_code' => '+359',
            ],
            [
                'iso_3166_2' => 'HR',
                'iso_3166_3' => 'HRV',
                'name_en' => 'Croatia',
                'name_de' => 'Kroatien',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+385',
            ],
            [
                'iso_3166_2' => 'CY',
                'iso_3166_3' => 'CYP',
                'name_en' => 'Cyprus',
                'name_de' => 'Zypern',
                'region' => 'Europe',
                'subregion' => 'Western Asia',
                'currency_code' => 'EUR',
                'phone_code' => '+357',
            ],
            [
                'iso_3166_2' => 'CZ',
                'iso_3166_3' => 'CZE',
                'name_en' => 'Czech Republic',
                'name_de' => 'Tschechien',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'currency_code' => 'CZK',
                'phone_code' => '+420',
            ],
            [
                'iso_3166_2' => 'DK',
                'iso_3166_3' => 'DNK',
                'name_en' => 'Denmark',
                'name_de' => 'Dänemark',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'DKK',
                'phone_code' => '+45',
            ],
            [
                'iso_3166_2' => 'EE',
                'iso_3166_3' => 'EST',
                'name_en' => 'Estonia',
                'name_de' => 'Estland',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+372',
            ],
            [
                'iso_3166_2' => 'FI',
                'iso_3166_3' => 'FIN',
                'name_en' => 'Finland',
                'name_de' => 'Finnland',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+358',
            ],
            [
                'iso_3166_2' => 'FR',
                'iso_3166_3' => 'FRA',
                'name_en' => 'France',
                'name_de' => 'Frankreich',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+33',
            ],
            [
                'iso_3166_2' => 'DE',
                'iso_3166_3' => 'DEU',
                'name_en' => 'Germany',
                'name_de' => 'Deutschland',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+49',
            ],
            [
                'iso_3166_2' => 'GR',
                'iso_3166_3' => 'GRC',
                'name_en' => 'Greece',
                'name_de' => 'Griechenland',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+30',
            ],
            [
                'iso_3166_2' => 'HU',
                'iso_3166_3' => 'HUN',
                'name_en' => 'Hungary',
                'name_de' => 'Ungarn',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'currency_code' => 'HUF',
                'phone_code' => '+36',
            ],
            [
                'iso_3166_2' => 'IS',
                'iso_3166_3' => 'ISL',
                'name_en' => 'Iceland',
                'name_de' => 'Island',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'ISK',
                'phone_code' => '+354',
            ],
            [
                'iso_3166_2' => 'IE',
                'iso_3166_3' => 'IRL',
                'name_en' => 'Ireland',
                'name_de' => 'Irland',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+353',
            ],
            [
                'iso_3166_2' => 'IT',
                'iso_3166_3' => 'ITA',
                'name_en' => 'Italy',
                'name_de' => 'Italien',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+39',
            ],
            [
                'iso_3166_2' => 'LV',
                'iso_3166_3' => 'LVA',
                'name_en' => 'Latvia',
                'name_de' => 'Lettland',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+371',
            ],
            [
                'iso_3166_2' => 'LI',
                'iso_3166_3' => 'LIE',
                'name_en' => 'Liechtenstein',
                'name_de' => 'Liechtenstein',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'CHF',
                'phone_code' => '+423',
            ],
            [
                'iso_3166_2' => 'LT',
                'iso_3166_3' => 'LTU',
                'name_en' => 'Lithuania',
                'name_de' => 'Litauen',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+370',
            ],
            [
                'iso_3166_2' => 'LU',
                'iso_3166_3' => 'LUX',
                'name_en' => 'Luxembourg',
                'name_de' => 'Luxemburg',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+352',
            ],
            [
                'iso_3166_2' => 'MT',
                'iso_3166_3' => 'MLT',
                'name_en' => 'Malta',
                'name_de' => 'Malta',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+356',
            ],
            [
                'iso_3166_2' => 'MD',
                'iso_3166_3' => 'MDA',
                'name_en' => 'Moldova',
                'name_de' => 'Moldau',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'currency_code' => 'MDL',
                'phone_code' => '+373',
            ],
            [
                'iso_3166_2' => 'MC',
                'iso_3166_3' => 'MCO',
                'name_en' => 'Monaco',
                'name_de' => 'Monaco',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+377',
            ],
            [
                'iso_3166_2' => 'ME',
                'iso_3166_3' => 'MNE',
                'name_en' => 'Montenegro',
                'name_de' => 'Montenegro',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+382',
            ],
            [
                'iso_3166_2' => 'NL',
                'iso_3166_3' => 'NLD',
                'name_en' => 'Netherlands',
                'name_de' => 'Niederlande',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+31',
            ],
            [
                'iso_3166_2' => 'MK',
                'iso_3166_3' => 'MKD',
                'name_en' => 'North Macedonia',
                'name_de' => 'Nordmazedonien',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'MKD',
                'phone_code' => '+389',
            ],
            [
                'iso_3166_2' => 'NO',
                'iso_3166_3' => 'NOR',
                'name_en' => 'Norway',
                'name_de' => 'Norwegen',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'NOK',
                'phone_code' => '+47',
            ],
            [
                'iso_3166_2' => 'PL',
                'iso_3166_3' => 'POL',
                'name_en' => 'Poland',
                'name_de' => 'Polen',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'currency_code' => 'PLN',
                'phone_code' => '+48',
            ],
            [
                'iso_3166_2' => 'PT',
                'iso_3166_3' => 'PRT',
                'name_en' => 'Portugal',
                'name_de' => 'Portugal',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+351',
            ],
            [
                'iso_3166_2' => 'RO',
                'iso_3166_3' => 'ROU',
                'name_en' => 'Romania',
                'name_de' => 'Rumänien',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'currency_code' => 'RON',
                'phone_code' => '+40',
            ],
            [
                'iso_3166_2' => 'RU',
                'iso_3166_3' => 'RUS',
                'name_en' => 'Russia',
                'name_de' => 'Russland',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'currency_code' => 'RUB',
                'phone_code' => '+7',
            ],
            [
                'iso_3166_2' => 'SM',
                'iso_3166_3' => 'SMR',
                'name_en' => 'San Marino',
                'name_de' => 'San Marino',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+378',
            ],
            [
                'iso_3166_2' => 'RS',
                'iso_3166_3' => 'SRB',
                'name_en' => 'Serbia',
                'name_de' => 'Serbien',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'RSD',
                'phone_code' => '+381',
            ],
            [
                'iso_3166_2' => 'SK',
                'iso_3166_3' => 'SVK',
                'name_en' => 'Slovakia',
                'name_de' => 'Slowakei',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+421',
            ],
            [
                'iso_3166_2' => 'SI',
                'iso_3166_3' => 'SVN',
                'name_en' => 'Slovenia',
                'name_de' => 'Slowenien',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+386',
            ],
            [
                'iso_3166_2' => 'ES',
                'iso_3166_3' => 'ESP',
                'name_en' => 'Spain',
                'name_de' => 'Spanien',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+34',
            ],
            [
                'iso_3166_2' => 'SE',
                'iso_3166_3' => 'SWE',
                'name_en' => 'Sweden',
                'name_de' => 'Schweden',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'SEK',
                'phone_code' => '+46',
            ],
            [
                'iso_3166_2' => 'CH',
                'iso_3166_3' => 'CHE',
                'name_en' => 'Switzerland',
                'name_de' => 'Schweiz',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'currency_code' => 'CHF',
                'phone_code' => '+41',
            ],
            [
                'iso_3166_2' => 'UA',
                'iso_3166_3' => 'UKR',
                'name_en' => 'Ukraine',
                'name_de' => 'Ukraine',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'currency_code' => 'UAH',
                'phone_code' => '+380',
            ],
            [
                'iso_3166_2' => 'GB',
                'iso_3166_3' => 'GBR',
                'name_en' => 'United Kingdom',
                'name_de' => 'Vereinigtes Königreich',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'currency_code' => 'GBP',
                'phone_code' => '+44',
            ],
            [
                'iso_3166_2' => 'VA',
                'iso_3166_3' => 'VAT',
                'name_en' => 'Vatican City',
                'name_de' => 'Vatikanstadt',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'currency_code' => 'EUR',
                'phone_code' => '+379',
            ],
            // -------------------------
            // AMERICAS
            // -------------------------
            [
                'iso_3166_2' => 'AG',
                'iso_3166_3' => 'ATG',
                'name_en' => 'Antigua and Barbuda',
                'name_de' => 'Antigua und Barbuda',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'currency_code' => 'XCD',
                'phone_code' => '+1-268',
            ],
            [
                'iso_3166_2' => 'AR',
                'iso_3166_3' => 'ARG',
                'name_en' => 'Argentina',
                'name_de' => 'Argentinien',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'ARS',
                'phone_code' => '+54',
            ],
            [
                'iso_3166_2' => 'BS',
                'iso_3166_3' => 'BHS',
                'name_en' => 'Bahamas',
                'name_de' => 'Bahamas',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'currency_code' => 'BSD',
                'phone_code' => '+1-242',
            ],
            [
                'iso_3166_2' => 'BB',
                'iso_3166_3' => 'BRB',
                'name_en' => 'Barbados',
                'name_de' => 'Barbados',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'currency_code' => 'BBD',
                'phone_code' => '+1-246',
            ],
            [
                'iso_3166_2' => 'BZ',
                'iso_3166_3' => 'BLZ',
                'name_en' => 'Belize',
                'name_de' => 'Belize',
                'region' => 'Americas',
                'subregion' => 'Central America',
                'currency_code' => 'BZD',
                'phone_code' => '+501',
            ],
            [
                'iso_3166_2' => 'BO',
                'iso_3166_3' => 'BOL',
                'name_en' => 'Bolivia',
                'name_de' => 'Bolivien',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'BOB',
                'phone_code' => '+591',
            ],
            [
                'iso_3166_2' => 'BR',
                'iso_3166_3' => 'BRA',
                'name_en' => 'Brazil',
                'name_de' => 'Brasilien',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'BRL',
                'phone_code' => '+55',
            ],
            [
                'iso_3166_2' => 'CA',
                'iso_3166_3' => 'CAN',
                'name_en' => 'Canada',
                'name_de' => 'Kanada',
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'currency_code' => 'CAD',
                'phone_code' => '+1',
            ],
            [
                'iso_3166_2' => 'CL',
                'iso_3166_3' => 'CHL',
                'name_en' => 'Chile',
                'name_de' => 'Chile',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'CLP',
                'phone_code' => '+56',
            ],
            [
                'iso_3166_2' => 'CO',
                'iso_3166_3' => 'COL',
                'name_en' => 'Colombia',
                'name_de' => 'Kolumbien',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'COP',
                'phone_code' => '+57',
            ],
            [
                'iso_3166_2' => 'CR',
                'iso_3166_3' => 'CRI',
                'name_en' => 'Costa Rica',
                'name_de' => 'Costa Rica',
                'region' => 'Americas',
                'subregion' => 'Central America',
                'currency_code' => 'CRC',
                'phone_code' => '+506',
            ],
            [
                'iso_3166_2' => 'CU',
                'iso_3166_3' => 'CUB',
                'name_en' => 'Cuba',
                'name_de' => 'Kuba',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'currency_code' => 'CUP',
                'phone_code' => '+53',
            ],
            [
                'iso_3166_2' => 'DM',
                'iso_3166_3' => 'DMA',
                'name_en' => 'Dominica',
                'name_de' => 'Dominica',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'currency_code' => 'XCD',
                'phone_code' => '+1-767',
            ],
            [
                'iso_3166_2' => 'DO',
                'iso_3166_3' => 'DOM',
                'name_en' => 'Dominican Republic',
                'name_de' => 'Dominikanische Republik',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'currency_code' => 'DOP',
                'phone_code' => '+1-809',
            ],
            [
                'iso_3166_2' => 'EC',
                'iso_3166_3' => 'ECU',
                'name_en' => 'Ecuador',
                'name_de' => 'Ecuador',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'USD',
                'phone_code' => '+593',
            ],
            [
                'iso_3166_2' => 'SV',
                'iso_3166_3' => 'SLV',
                'name_en' => 'El Salvador',
                'name_de' => 'El Salvador',
                'region' => 'Americas',
                'subregion' => 'Central America',
                'currency_code' => 'USD',
                'phone_code' => '+503',
            ],
            [
                'iso_3166_2' => 'GD',
                'iso_3166_3' => 'GRD',
                'name_en' => 'Grenada',
                'name_de' => 'Grenada',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'currency_code' => 'XCD',
                'phone_code' => '+1-473',
            ],
            [
                'iso_3166_2' => 'GT',
                'iso_3166_3' => 'GTM',
                'name_en' => 'Guatemala',
                'name_de' => 'Guatemala',
                'region' => 'Americas',
                'subregion' => 'Central America',
                'currency_code' => 'GTQ',
                'phone_code' => '+502',
            ],
            [
                'iso_3166_2' => 'GY',
                'iso_3166_3' => 'GUY',
                'name_en' => 'Guyana',
                'name_de' => 'Guyana',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'GYD',
                'phone_code' => '+592',
            ],
            [
                'iso_3166_2' => 'HT',
                'iso_3166_3' => 'HTI',
                'name_en' => 'Haiti',
                'name_de' => 'Haiti',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'currency_code' => 'HTG',
                'phone_code' => '+509',
            ],
            [
                'iso_3166_2' => 'HN',
                'iso_3166_3' => 'HND',
                'name_en' => 'Honduras',
                'name_de' => 'Honduras',
                'region' => 'Americas',
                'subregion' => 'Central America',
                'currency_code' => 'HNL',
                'phone_code' => '+504',
            ],
            [
                'iso_3166_2' => 'JM',
                'iso_3166_3' => 'JAM',
                'name_en' => 'Jamaica',
                'name_de' => 'Jamaika',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'currency_code' => 'JMD',
                'phone_code' => '+1-876',
            ],
            [
                'iso_3166_2' => 'MX',
                'iso_3166_3' => 'MEX',
                'name_en' => 'Mexico',
                'name_de' => 'Mexiko',
                'region' => 'Americas',
                'subregion' => 'North America',
                'currency_code' => 'MXN',
                'phone_code' => '+52',
            ],
            [
                'iso_3166_2' => 'NI',
                'iso_3166_3' => 'NIC',
                'name_en' => 'Nicaragua',
                'name_de' => 'Nicaragua',
                'region' => 'Americas',
                'subregion' => 'Central America',
                'currency_code' => 'NIO',
                'phone_code' => '+505',
            ],
            [
                'iso_3166_2' => 'PA',
                'iso_3166_3' => 'PAN',
                'name_en' => 'Panama',
                'name_de' => 'Panama',
                'region' => 'Americas',
                'subregion' => 'Central America',
                'currency_code' => 'PAB',
                'phone_code' => '+507',
            ],
            [
                'iso_3166_2' => 'PY',
                'iso_3166_3' => 'PRY',
                'name_en' => 'Paraguay',
                'name_de' => 'Paraguay',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'PYG',
                'phone_code' => '+595',
            ],
            [
                'iso_3166_2' => 'PE',
                'iso_3166_3' => 'PER',
                'name_en' => 'Peru',
                'name_de' => 'Peru',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'PEN',
                'phone_code' => '+51',
            ],
            [
                'iso_3166_2' => 'KN',
                'iso_3166_3' => 'KNA',
                'name_en' => 'Saint Kitts and Nevis',
                'name_de' => 'St. Kitts und Nevis',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'currency_code' => 'XCD',
                'phone_code' => '+1-869',
            ],
            [
                'iso_3166_2' => 'LC',
                'iso_3166_3' => 'LCA',
                'name_en' => 'Saint Lucia',
                'name_de' => 'St. Lucia',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'currency_code' => 'XCD',
                'phone_code' => '+1-758',
            ],
            [
                'iso_3166_2' => 'VC',
                'iso_3166_3' => 'VCT',
                'name_en' => 'Saint Vincent and the Grenadines',
                'name_de' => 'St. Vincent und die Grenadinen',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'currency_code' => 'XCD',
                'phone_code' => '+1-784',
            ],
            [
                'iso_3166_2' => 'SR',
                'iso_3166_3' => 'SUR',
                'name_en' => 'Suriname',
                'name_de' => 'Suriname',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'SRD',
                'phone_code' => '+597',
            ],
            [
                'iso_3166_2' => 'TT',
                'iso_3166_3' => 'TTO',
                'name_en' => 'Trinidad and Tobago',
                'name_de' => 'Trinidad und Tobago',
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'currency_code' => 'TTD',
                'phone_code' => '+1-868',
            ],
            [
                'iso_3166_2' => 'UY',
                'iso_3166_3' => 'URY',
                'name_en' => 'Uruguay',
                'name_de' => 'Uruguay',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'UYU',
                'phone_code' => '+598',
            ],
            [
                'iso_3166_2' => 'VE',
                'iso_3166_3' => 'VEN',
                'name_en' => 'Venezuela',
                'name_de' => 'Venezuela',
                'region' => 'Americas',
                'subregion' => 'South America',
                'currency_code' => 'VES',
                'phone_code' => '+58',
            ],
            [
                'iso_3166_2' => 'US',
                'iso_3166_3' => 'USA',
                'name_en' => 'United States',
                'name_de' => 'Vereinigte Staaten',
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'currency_code' => 'USD',
                'phone_code' => '+1',
            ],
            // -------------------------
            // AFRICA
            // -------------------------
            [
                'iso_3166_2' => 'DZ',
                'iso_3166_3' => 'DZA',
                'name_en' => 'Algeria',
                'name_de' => 'Algerien',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'currency_code' => 'DZD',
                'phone_code' => '+213',
            ],
            [
                'iso_3166_2' => 'AO',
                'iso_3166_3' => 'AGO',
                'name_en' => 'Angola',
                'name_de' => 'Angola',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'currency_code' => 'AOA',
                'phone_code' => '+244',
            ],
            [
                'iso_3166_2' => 'BJ',
                'iso_3166_3' => 'BEN',
                'name_en' => 'Benin',
                'name_de' => 'Benin',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'XOF',
                'phone_code' => '+229',
            ],
            [
                'iso_3166_2' => 'BW',
                'iso_3166_3' => 'BWA',
                'name_en' => 'Botswana',
                'name_de' => 'Botswana',
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'currency_code' => 'BWP',
                'phone_code' => '+267',
            ],
            [
                'iso_3166_2' => 'BF',
                'iso_3166_3' => 'BFA',
                'name_en' => 'Burkina Faso',
                'name_de' => 'Burkina Faso',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'XOF',
                'phone_code' => '+226',
            ],
            [
                'iso_3166_2' => 'BI',
                'iso_3166_3' => 'BDI',
                'name_en' => 'Burundi',
                'name_de' => 'Burundi',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'BIF',
                'phone_code' => '+257',
            ],
            [
                'iso_3166_2' => 'CM',
                'iso_3166_3' => 'CMR',
                'name_en' => 'Cameroon',
                'name_de' => 'Kamerun',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'currency_code' => 'XAF',
                'phone_code' => '+237',
            ],
            [
                'iso_3166_2' => 'CV',
                'iso_3166_3' => 'CPV',
                'name_en' => 'Cabo Verde',
                'name_de' => 'Kap Verde',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'CVE',
                'phone_code' => '+238',
            ],
            [
                'iso_3166_2' => 'CF',
                'iso_3166_3' => 'CAF',
                'name_en' => 'Central African Republic',
                'name_de' => 'Zentralafrikanische Republik',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'currency_code' => 'XAF',
                'phone_code' => '+236',
            ],
            [
                'iso_3166_2' => 'TD',
                'iso_3166_3' => 'TCD',
                'name_en' => 'Chad',
                'name_de' => 'Tschad',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'currency_code' => 'XAF',
                'phone_code' => '+235',
            ],
            [
                'iso_3166_2' => 'KM',
                'iso_3166_3' => 'COM',
                'name_en' => 'Comoros',
                'name_de' => 'Komoren',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'KMF',
                'phone_code' => '+269',
            ],
            [
                'iso_3166_2' => 'CG',
                'iso_3166_3' => 'COG',
                'name_en' => 'Republic of the Congo',
                'name_de' => 'Kongo (Republik)',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'currency_code' => 'XAF',
                'phone_code' => '+242',
            ],
            [
                'iso_3166_2' => 'CD',
                'iso_3166_3' => 'COD',
                'name_en' => 'Democratic Republic of the Congo',
                'name_de' => 'Kongo (Demokratische Republik)',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'currency_code' => 'CDF',
                'phone_code' => '+243',
            ],
            [
                'iso_3166_2' => 'CI',
                'iso_3166_3' => 'CIV',
                'name_en' => 'Ivory Coast',
                'name_de' => 'Elfenbeinküste',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'XOF',
                'phone_code' => '+225',
            ],
            [
                'iso_3166_2' => 'DJ',
                'iso_3166_3' => 'DJI',
                'name_en' => 'Djibouti',
                'name_de' => 'Dschibuti',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'DJF',
                'phone_code' => '+253',
            ],
            [
                'iso_3166_2' => 'EG',
                'iso_3166_3' => 'EGY',
                'name_en' => 'Egypt',
                'name_de' => 'Ägypten',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'currency_code' => 'EGP',
                'phone_code' => '+20',
            ],
            [
                'iso_3166_2' => 'GQ',
                'iso_3166_3' => 'GNQ',
                'name_en' => 'Equatorial Guinea',
                'name_de' => 'Äquatorialguinea',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'currency_code' => 'XAF',
                'phone_code' => '+240',
            ],
            [
                'iso_3166_2' => 'ER',
                'iso_3166_3' => 'ERI',
                'name_en' => 'Eritrea',
                'name_de' => 'Eritrea',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'ERN',
                'phone_code' => '+291',
            ],
            [
                'iso_3166_2' => 'SZ',
                'iso_3166_3' => 'SWZ',
                'name_en' => 'Eswatini',
                'name_de' => 'Eswatini',
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'currency_code' => 'SZL',
                'phone_code' => '+268',
            ],
            [
                'iso_3166_2' => 'ET',
                'iso_3166_3' => 'ETH',
                'name_en' => 'Ethiopia',
                'name_de' => 'Äthiopien',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'ETB',
                'phone_code' => '+251',
            ],
            [
                'iso_3166_2' => 'GA',
                'iso_3166_3' => 'GAB',
                'name_en' => 'Gabon',
                'name_de' => 'Gabun',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'currency_code' => 'XAF',
                'phone_code' => '+241',
            ],
            [
                'iso_3166_2' => 'GM',
                'iso_3166_3' => 'GMB',
                'name_en' => 'The Gambia',
                'name_de' => 'Gambia',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'GMD',
                'phone_code' => '+220',
            ],
            [
                'iso_3166_2' => 'GH',
                'iso_3166_3' => 'GHA',
                'name_en' => 'Ghana',
                'name_de' => 'Ghana',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'GHS',
                'phone_code' => '+233',
            ],
            [
                'iso_3166_2' => 'GN',
                'iso_3166_3' => 'GIN',
                'name_en' => 'Guinea',
                'name_de' => 'Guinea',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'GNF',
                'phone_code' => '+224',
            ],
            [
                'iso_3166_2' => 'GW',
                'iso_3166_3' => 'GNB',
                'name_en' => 'Guinea-Bissau',
                'name_de' => 'Guinea-Bissau',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'XOF',
                'phone_code' => '+245',
            ],
            [
                'iso_3166_2' => 'KE',
                'iso_3166_3' => 'KEN',
                'name_en' => 'Kenya',
                'name_de' => 'Kenia',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'KES',
                'phone_code' => '+254',
            ],
            [
                'iso_3166_2' => 'LS',
                'iso_3166_3' => 'LSO',
                'name_en' => 'Lesotho',
                'name_de' => 'Lesotho',
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'currency_code' => 'LSL',
                'phone_code' => '+266',
            ],
            [
                'iso_3166_2' => 'LR',
                'iso_3166_3' => 'LBR',
                'name_en' => 'Liberia',
                'name_de' => 'Liberia',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'LRD',
                'phone_code' => '+231',
            ],
            [
                'iso_3166_2' => 'LY',
                'iso_3166_3' => 'LBY',
                'name_en' => 'Libya',
                'name_de' => 'Libyen',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'currency_code' => 'LYD',
                'phone_code' => '+218',
            ],
            [
                'iso_3166_2' => 'MG',
                'iso_3166_3' => 'MDG',
                'name_en' => 'Madagascar',
                'name_de' => 'Madagaskar',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'MGA',
                'phone_code' => '+261',
            ],
            [
                'iso_3166_2' => 'MW',
                'iso_3166_3' => 'MWI',
                'name_en' => 'Malawi',
                'name_de' => 'Malawi',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'MWK',
                'phone_code' => '+265',
            ],
            [
                'iso_3166_2' => 'ML',
                'iso_3166_3' => 'MLI',
                'name_en' => 'Mali',
                'name_de' => 'Mali',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'XOF',
                'phone_code' => '+223',
            ],
            [
                'iso_3166_2' => 'MR',
                'iso_3166_3' => 'MRT',
                'name_en' => 'Mauritania',
                'name_de' => 'Mauretanien',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'MRU',
                'phone_code' => '+222',
            ],
            [
                'iso_3166_2' => 'MU',
                'iso_3166_3' => 'MUS',
                'name_en' => 'Mauritius',
                'name_de' => 'Mauritius',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'MUR',
                'phone_code' => '+230',
            ],
            [
                'iso_3166_2' => 'MA',
                'iso_3166_3' => 'MAR',
                'name_en' => 'Morocco',
                'name_de' => 'Marokko',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'currency_code' => 'MAD',
                'phone_code' => '+212',
            ],
            [
                'iso_3166_2' => 'MZ',
                'iso_3166_3' => 'MOZ',
                'name_en' => 'Mozambique',
                'name_de' => 'Mosambik',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'MZN',
                'phone_code' => '+258',
            ],
            [
                'iso_3166_2' => 'NA',
                'iso_3166_3' => 'NAM',
                'name_en' => 'Namibia',
                'name_de' => 'Namibia',
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'currency_code' => 'NAD',
                'phone_code' => '+264',
            ],
            [
                'iso_3166_2' => 'NE',
                'iso_3166_3' => 'NER',
                'name_en' => 'Niger',
                'name_de' => 'Niger',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'XOF',
                'phone_code' => '+227',
            ],
            [
                'iso_3166_2' => 'NG',
                'iso_3166_3' => 'NGA',
                'name_en' => 'Nigeria',
                'name_de' => 'Nigeria',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'NGN',
                'phone_code' => '+234',
            ],
            [
                'iso_3166_2' => 'RW',
                'iso_3166_3' => 'RWA',
                'name_en' => 'Rwanda',
                'name_de' => 'Ruanda',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'RWF',
                'phone_code' => '+250',
            ],
            [
                'iso_3166_2' => 'ST',
                'iso_3166_3' => 'STP',
                'name_en' => 'São Tomé and Príncipe',
                'name_de' => 'São Tomé und Príncipe',
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'currency_code' => 'STN',
                'phone_code' => '+239',
            ],
            [
                'iso_3166_2' => 'SN',
                'iso_3166_3' => 'SEN',
                'name_en' => 'Senegal',
                'name_de' => 'Senegal',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'XOF',
                'phone_code' => '+221',
            ],
            [
                'iso_3166_2' => 'SC',
                'iso_3166_3' => 'SYC',
                'name_en' => 'Seychelles',
                'name_de' => 'Seychellen',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'SCR',
                'phone_code' => '+248',
            ],
            [
                'iso_3166_2' => 'SL',
                'iso_3166_3' => 'SLE',
                'name_en' => 'Sierra Leone',
                'name_de' => 'Sierra Leone',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'SLL',
                'phone_code' => '+232',
            ],
            [
                'iso_3166_2' => 'SO',
                'iso_3166_3' => 'SOM',
                'name_en' => 'Somalia',
                'name_de' => 'Somalia',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'SOS',
                'phone_code' => '+252',
            ],
            [
                'iso_3166_2' => 'ZA',
                'iso_3166_3' => 'ZAF',
                'name_en' => 'South Africa',
                'name_de' => 'Südafrika',
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'currency_code' => 'ZAR',
                'phone_code' => '+27',
            ],
            [
                'iso_3166_2' => 'SS',
                'iso_3166_3' => 'SSD',
                'name_en' => 'South Sudan',
                'name_de' => 'Südsudan',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'SSP',
                'phone_code' => '+211',
            ],
            [
                'iso_3166_2' => 'SD',
                'iso_3166_3' => 'SDN',
                'name_en' => 'Sudan',
                'name_de' => 'Sudan',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'currency_code' => 'SDG',
                'phone_code' => '+249',
            ],
            [
                'iso_3166_2' => 'TZ',
                'iso_3166_3' => 'TZA',
                'name_en' => 'Tanzania',
                'name_de' => 'Tansania',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'TZS',
                'phone_code' => '+255',
            ],
            [
                'iso_3166_2' => 'TG',
                'iso_3166_3' => 'TGO',
                'name_en' => 'Togo',
                'name_de' => 'Togo',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'currency_code' => 'XOF',
                'phone_code' => '+228',
            ],
            [
                'iso_3166_2' => 'TN',
                'iso_3166_3' => 'TUN',
                'name_en' => 'Tunisia',
                'name_de' => 'Tunesien',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'currency_code' => 'TND',
                'phone_code' => '+216',
            ],
            [
                'iso_3166_2' => 'UG',
                'iso_3166_3' => 'UGA',
                'name_en' => 'Uganda',
                'name_de' => 'Uganda',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'UGX',
                'phone_code' => '+256',
            ],
            [
                'iso_3166_2' => 'ZM',
                'iso_3166_3' => 'ZMB',
                'name_en' => 'Zambia',
                'name_de' => 'Zambia',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'ZMW',
                'phone_code' => '+260',
            ],
            [
                'iso_3166_2' => 'ZW',
                'iso_3166_3' => 'ZWE',
                'name_en' => 'Zimbabwe',
                'name_de' => 'Zimbabwe',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'currency_code' => 'ZWL',
                'phone_code' => '+263',
            ],
            // -------------------------
            // ASIA
            // -------------------------
            [
                'iso_3166_2' => 'AF',
                'iso_3166_3' => 'AFG',
                'name_en' => 'Afghanistan',
                'name_de' => 'Afghanistan',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'currency_code' => 'AFN',
                'phone_code' => '+93',
            ],
            [
                'iso_3166_2' => 'AM',
                'iso_3166_3' => 'ARM',
                'name_en' => 'Armenia',
                'name_de' => 'Armenien',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'AMD',
                'phone_code' => '+374',
            ],
            [
                'iso_3166_2' => 'AZ',
                'iso_3166_3' => 'AZE',
                'name_en' => 'Azerbaijan',
                'name_de' => 'Aserbaidschan',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'AZN',
                'phone_code' => '+994',
            ],
            [
                'iso_3166_2' => 'BH',
                'iso_3166_3' => 'BHR',
                'name_en' => 'Bahrain',
                'name_de' => 'Bahrain',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'BHD',
                'phone_code' => '+973',
            ],
            [
                'iso_3166_2' => 'BD',
                'iso_3166_3' => 'BGD',
                'name_en' => 'Bangladesh',
                'name_de' => 'Bangladesch',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'currency_code' => 'BDT',
                'phone_code' => '+880',
            ],
            [
                'iso_3166_2' => 'BT',
                'iso_3166_3' => 'BTN',
                'name_en' => 'Bhutan',
                'name_de' => 'Bhutan',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'currency_code' => 'BTN',
                'phone_code' => '+975',
            ],
            [
                'iso_3166_2' => 'BN',
                'iso_3166_3' => 'BRN',
                'name_en' => 'Brunei',
                'name_de' => 'Brunei',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'BND',
                'phone_code' => '+673',
            ],
            [
                'iso_3166_2' => 'KH',
                'iso_3166_3' => 'KHM',
                'name_en' => 'Cambodia',
                'name_de' => 'Kambodscha',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'KHR',
                'phone_code' => '+855',
            ],
            [
                'iso_3166_2' => 'CN',
                'iso_3166_3' => 'CHN',
                'name_en' => 'China',
                'name_de' => 'China',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'CNY',
                'phone_code' => '+86',
            ],
            [
                'iso_3166_2' => 'GE',
                'iso_3166_3' => 'GEO',
                'name_en' => 'Georgia',
                'name_de' => 'Georgien',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'GEL',
                'phone_code' => '+995',
            ],
            [
                'iso_3166_2' => 'HK',
                'iso_3166_3' => 'HKG',
                'name_en' => 'Hong Kong',
                'name_de' => 'Hongkong',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'HKD',
                'phone_code' => '+852',
            ],
            [
                'iso_3166_2' => 'IN',
                'iso_3166_3' => 'IND',
                'name_en' => 'India',
                'name_de' => 'Indien',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'currency_code' => 'INR',
                'phone_code' => '+91',
            ],
            [
                'iso_3166_2' => 'ID',
                'iso_3166_3' => 'IDN',
                'name_en' => 'Indonesia',
                'name_de' => 'Indonesien',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'IDR',
                'phone_code' => '+62',
            ],
            [
                'iso_3166_2' => 'IR',
                'iso_3166_3' => 'IRN',
                'name_en' => 'Iran',
                'name_de' => 'Iran',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'currency_code' => 'IRR',
                'phone_code' => '+98',
            ],
            [
                'iso_3166_2' => 'IQ',
                'iso_3166_3' => 'IRQ',
                'name_en' => 'Iraq',
                'name_de' => 'Irak',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'IQD',
                'phone_code' => '+964',
            ],
            [
                'iso_3166_2' => 'IL',
                'iso_3166_3' => 'ISR',
                'name_en' => 'Israel',
                'name_de' => 'Israel',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'ILS',
                'phone_code' => '+972',
            ],
            [
                'iso_3166_2' => 'JP',
                'iso_3166_3' => 'JPN',
                'name_en' => 'Japan',
                'name_de' => 'Japan',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'JPY',
                'phone_code' => '+81',
            ],
            [
                'iso_3166_2' => 'JO',
                'iso_3166_3' => 'JOR',
                'name_en' => 'Jordan',
                'name_de' => 'Jordanien',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'JOD',
                'phone_code' => '+962',
            ],
            [
                'iso_3166_2' => 'KZ',
                'iso_3166_3' => 'KAZ',
                'name_en' => 'Kazakhstan',
                'name_de' => 'Kasachstan',
                'region' => 'Asia',
                'subregion' => 'Central Asia',
                'currency_code' => 'KZT',
                'phone_code' => '+7',
            ],
            [
                'iso_3166_2' => 'KW',
                'iso_3166_3' => 'KWT',
                'name_en' => 'Kuwait',
                'name_de' => 'Kuwait',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'KWD',
                'phone_code' => '+965',
            ],
            [
                'iso_3166_2' => 'KG',
                'iso_3166_3' => 'KGZ',
                'name_en' => 'Kyrgyzstan',
                'name_de' => 'Kirgisistan',
                'region' => 'Asia',
                'subregion' => 'Central Asia',
                'currency_code' => 'KGS',
                'phone_code' => '+996',
            ],
            [
                'iso_3166_2' => 'LA',
                'iso_3166_3' => 'LAO',
                'name_en' => 'Laos',
                'name_de' => 'Laos',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'LAK',
                'phone_code' => '+856',
            ],
            [
                'iso_3166_2' => 'LB',
                'iso_3166_3' => 'LBN',
                'name_en' => 'Lebanon',
                'name_de' => 'Libanon',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'LBP',
                'phone_code' => '+961',
            ],
            [
                'iso_3166_2' => 'MO',
                'iso_3166_3' => 'MAC',
                'name_en' => 'Macau',
                'name_de' => 'Macau',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'MOP',
                'phone_code' => '+853',
            ],
            [
                'iso_3166_2' => 'MY',
                'iso_3166_3' => 'MYS',
                'name_en' => 'Malaysia',
                'name_de' => 'Malaysia',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'MYR',
                'phone_code' => '+60',
            ],
            [
                'iso_3166_2' => 'MV',
                'iso_3166_3' => 'MDV',
                'name_en' => 'Maldives',
                'name_de' => 'Malediven',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'currency_code' => 'MVR',
                'phone_code' => '+960',
            ],
            [
                'iso_3166_2' => 'MN',
                'iso_3166_3' => 'MNG',
                'name_en' => 'Mongolia',
                'name_de' => 'Mongolei',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'MNT',
                'phone_code' => '+976',
            ],
            [
                'iso_3166_2' => 'MM',
                'iso_3166_3' => 'MMR',
                'name_en' => 'Myanmar',
                'name_de' => 'Myanmar',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'MMK',
                'phone_code' => '+95',
            ],
            [
                'iso_3166_2' => 'NP',
                'iso_3166_3' => 'NPL',
                'name_en' => 'Nepal',
                'name_de' => 'Nepal',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'currency_code' => 'NPR',
                'phone_code' => '+977',
            ],
            [
                'iso_3166_2' => 'KP',
                'iso_3166_3' => 'PRK',
                'name_en' => 'North Korea',
                'name_de' => 'Nordkorea',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'KPW',
                'phone_code' => '+850',
            ],
            [
                'iso_3166_2' => 'OM',
                'iso_3166_3' => 'OMN',
                'name_en' => 'Oman',
                'name_de' => 'Oman',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'OMR',
                'phone_code' => '+968',
            ],
            [
                'iso_3166_2' => 'PK',
                'iso_3166_3' => 'PAK',
                'name_en' => 'Pakistan',
                'name_de' => 'Pakistan',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'currency_code' => 'PKR',
                'phone_code' => '+92',
            ],
            [
                'iso_3166_2' => 'PS',
                'iso_3166_3' => 'PSE',
                'name_en' => 'Palestine',
                'name_de' => 'Palästina',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => null,
                'phone_code' => '+970',
            ],
            [
                'iso_3166_2' => 'PH',
                'iso_3166_3' => 'PHL',
                'name_en' => 'Philippines',
                'name_de' => 'Philippinen',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'PHP',
                'phone_code' => '+63',
            ],
            [
                'iso_3166_2' => 'QA',
                'iso_3166_3' => 'QAT',
                'name_en' => 'Qatar',
                'name_de' => 'Katar',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'QAR',
                'phone_code' => '+974',
            ],
            [
                'iso_3166_2' => 'SA',
                'iso_3166_3' => 'SAU',
                'name_en' => 'Saudi Arabia',
                'name_de' => 'Saudi-Arabien',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'SAR',
                'phone_code' => '+966',
            ],
            [
                'iso_3166_2' => 'SG',
                'iso_3166_3' => 'SGP',
                'name_en' => 'Singapore',
                'name_de' => 'Singapur',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'SGD',
                'phone_code' => '+65',
            ],
            [
                'iso_3166_2' => 'KR',
                'iso_3166_3' => 'KOR',
                'name_en' => 'South Korea',
                'name_de' => 'Südkorea',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'KRW',
                'phone_code' => '+82',
            ],
            [
                'iso_3166_2' => 'LK',
                'iso_3166_3' => 'LKA',
                'name_en' => 'Sri Lanka',
                'name_de' => 'Sri Lanka',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'currency_code' => 'LKR',
                'phone_code' => '+94',
            ],
            [
                'iso_3166_2' => 'SY',
                'iso_3166_3' => 'SYR',
                'name_en' => 'Syria',
                'name_de' => 'Syrien',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'SYP',
                'phone_code' => '+963',
            ],
            [
                'iso_3166_2' => 'TW',
                'iso_3166_3' => 'TWN',
                'name_en' => 'Taiwan',
                'name_de' => 'Taiwan',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'currency_code' => 'TWD',
                'phone_code' => '+886',
            ],
            [
                'iso_3166_2' => 'TJ',
                'iso_3166_3' => 'TJK',
                'name_en' => 'Tajikistan',
                'name_de' => 'Tadschikistan',
                'region' => 'Asia',
                'subregion' => 'Central Asia',
                'currency_code' => 'TJS',
                'phone_code' => '+992',
            ],
            [
                'iso_3166_2' => 'TH',
                'iso_3166_3' => 'THA',
                'name_en' => 'Thailand',
                'name_de' => 'Thailand',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'THB',
                'phone_code' => '+66',
            ],
            [
                'iso_3166_2' => 'TL',
                'iso_3166_3' => 'TLS',
                'name_en' => 'Timor-Leste',
                'name_de' => 'Osttimor',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'USD',
                'phone_code' => '+670',
            ],
            [
                'iso_3166_2' => 'TR',
                'iso_3166_3' => 'TUR',
                'name_en' => 'Turkey',
                'name_de' => 'Türkei',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'TRY',
                'phone_code' => '+90',
            ],
            [
                'iso_3166_2' => 'TM',
                'iso_3166_3' => 'TKM',
                'name_en' => 'Turkmenistan',
                'name_de' => 'Turkmenistan',
                'region' => 'Asia',
                'subregion' => 'Central Asia',
                'currency_code' => 'TMT',
                'phone_code' => '+993',
            ],
            [
                'iso_3166_2' => 'AE',
                'iso_3166_3' => 'ARE',
                'name_en' => 'United Arab Emirates',
                'name_de' => 'Vereinigte Arabische Emirate',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'AED',
                'phone_code' => '+971',
            ],
            [
                'iso_3166_2' => 'UZ',
                'iso_3166_3' => 'UZB',
                'name_en' => 'Uzbekistan',
                'name_de' => 'Usbekistan',
                'region' => 'Asia',
                'subregion' => 'Central Asia',
                'currency_code' => 'UZS',
                'phone_code' => '+998',
            ],
            [
                'iso_3166_2' => 'VN',
                'iso_3166_3' => 'VNM',
                'name_en' => 'Vietnam',
                'name_de' => 'Vietnam',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'currency_code' => 'VND',
                'phone_code' => '+84',
            ],
            [
                'iso_3166_2' => 'YE',
                'iso_3166_3' => 'YEM',
                'name_en' => 'Yemen',
                'name_de' => 'Jemen',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'currency_code' => 'YER',
                'phone_code' => '+967',
            ],
            // -------------------------
            // OCEANIA
            // -------------------------
            [
                'iso_3166_2' => 'AS',
                'iso_3166_3' => 'ASM',
                'name_en' => 'American Samoa',
                'name_de' => 'Amerikanisch-Samoa',
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'currency_code' => 'USD',
                'phone_code' => '+1-684',
            ],
            [
                'iso_3166_2' => 'AU',
                'iso_3166_3' => 'AUS',
                'name_en' => 'Australia',
                'name_de' => 'Australien',
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'currency_code' => 'AUD',
                'phone_code' => '+61',
            ],
            [
                'iso_3166_2' => 'CK',
                'iso_3166_3' => 'COK',
                'name_en' => 'Cook Islands',
                'name_de' => 'Cookinseln',
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'currency_code' => 'NZD',
                'phone_code' => '+682',
            ],
            [
                'iso_3166_2' => 'FJ',
                'iso_3166_3' => 'FJI',
                'name_en' => 'Fiji',
                'name_de' => 'Fidschi',
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
                'currency_code' => 'FJD',
                'phone_code' => '+679',
            ],
            [
                'iso_3166_2' => 'PF',
                'iso_3166_3' => 'PYF',
                'name_en' => 'French Polynesia',
                'name_de' => 'Französisch-Polynesien',
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'currency_code' => 'XPF',
                'phone_code' => '+689',
            ],
            [
                'iso_3166_2' => 'GU',
                'iso_3166_3' => 'GUM',
                'name_en' => 'Guam',
                'name_de' => 'Guam',
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'currency_code' => 'USD',
                'phone_code' => '+1-671',
            ],
            [
                'iso_3166_2' => 'KI',
                'iso_3166_3' => 'KIR',
                'name_en' => 'Kiribati',
                'name_de' => 'Kiribati',
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'currency_code' => 'AUD',
                'phone_code' => '+686',
            ],
            [
                'iso_3166_2' => 'MH',
                'iso_3166_3' => 'MHL',
                'name_en' => 'Marshall Islands',
                'name_de' => 'Marshallinseln',
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'currency_code' => 'USD',
                'phone_code' => '+692',
            ],
            [
                'iso_3166_2' => 'FM',
                'iso_3166_3' => 'FSM',
                'name_en' => 'Micronesia',
                'name_de' => 'Mikronesien',
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'currency_code' => 'USD',
                'phone_code' => '+691',
            ],
            [
                'iso_3166_2' => 'NR',
                'iso_3166_3' => 'NRU',
                'name_en' => 'Nauru',
                'name_de' => 'Nauru',
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'currency_code' => 'AUD',
                'phone_code' => '+674',
            ],
            [
                'iso_3166_2' => 'NC',
                'iso_3166_3' => 'NCL',
                'name_en' => 'New Caledonia',
                'name_de' => 'Neukaledonien',
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
                'currency_code' => 'XPF',
                'phone_code' => '+687',
            ],
            [
                'iso_3166_2' => 'NZ',
                'iso_3166_3' => 'NZL',
                'name_en' => 'New Zealand',
                'name_de' => 'Neuseeland',
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'currency_code' => 'NZD',
                'phone_code' => '+64',
            ],
            [
                'iso_3166_2' => 'NU',
                'iso_3166_3' => 'NIU',
                'name_en' => 'Niue',
                'name_de' => 'Niue',
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'currency_code' => 'NZD',
                'phone_code' => '+683',
            ],
            [
                'iso_3166_2' => 'MP',
                'iso_3166_3' => 'MNP',
                'name_en' => 'Northern Mariana Islands',
                'name_de' => 'Nördliche Marianen',
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'currency_code' => 'USD',
                'phone_code' => '+1-670',
            ],
            [
                'iso_3166_2' => 'PW',
                'iso_3166_3' => 'PLW',
                'name_en' => 'Palau',
                'name_de' => 'Palau',
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'currency_code' => 'USD',
                'phone_code' => '+680',
            ],
            [
                'iso_3166_2' => 'PG',
                'iso_3166_3' => 'PNG',
                'name_en' => 'Papua New Guinea',
                'name_de' => 'Papua-Neuguinea',
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
                'currency_code' => 'PGK',
                'phone_code' => '+675',
            ],
            [
                'iso_3166_2' => 'WS',
                'iso_3166_3' => 'WSM',
                'name_en' => 'Samoa',
                'name_de' => 'Samoa',
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'currency_code' => 'WST',
                'phone_code' => '+685',
            ],
            [
                'iso_3166_2' => 'SB',
                'iso_3166_3' => 'SLB',
                'name_en' => 'Solomon Islands',
                'name_de' => 'Salomonen',
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
                'currency_code' => 'SBD',
                'phone_code' => '+677',
            ],
            [
                'iso_3166_2' => 'TO',
                'iso_3166_3' => 'TON',
                'name_en' => 'Tonga',
                'name_de' => 'Tonga',
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'currency_code' => 'TOP',
                'phone_code' => '+676',
            ],
            [
                'iso_3166_2' => 'TV',
                'iso_3166_3' => 'TUV',
                'name_en' => 'Tuvalu',
                'name_de' => 'Tuvalu',
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'currency_code' => 'AUD',
                'phone_code' => '+688',
            ],
            [
                'iso_3166_2' => 'VU',
                'iso_3166_3' => 'VUT',
                'name_en' => 'Vanuatu',
                'name_de' => 'Vanuatu',
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
                'currency_code' => 'VUV',
                'phone_code' => '+678',
            ],
            // -------------------------
            // SPECIAL TERRITORIES
            // -------------------------
            [
                'iso_3166_2' => 'AQ',
                'iso_3166_3' => 'ATA',
                'name_en' => 'Antarctica',
                'name_de' => 'Antarktis',
                'region' => 'Antarctica',
                'subregion' => null,
                'currency_code' => null,
                'phone_code' => null,
            ],
            [
                'iso_3166_2' => 'BV',
                'iso_3166_3' => 'BVT',
                'name_en' => 'Bouvet Island',
                'name_de' => 'Bouvetinsel',
                'region' => 'Antarctica',
                'subregion' => null,
                'currency_code' => null,
                'phone_code' => null,
            ],
            [
                'iso_3166_2' => 'TF',
                'iso_3166_3' => 'ATF',
                'name_en' => 'French Southern Territories',
                'name_de' => 'Französische Südgebiete',
                'region' => 'Antarctica',
                'subregion' => null,
                'currency_code' => 'EUR',
                'phone_code' => null,
            ],
            [
                'iso_3166_2' => 'HM',
                'iso_3166_3' => 'HMD',
                'name_en' => 'Heard Island and McDonald Islands',
                'name_de' => 'Heard und McDonaldinseln',
                'region' => 'Antarctica',
                'subregion' => null,
                'currency_code' => 'AUD',
                'phone_code' => null,
            ],
        ];

        DB::table('countries')->truncate();

        foreach ($countries as $c) {
            DB::table('countries')->insert([
                'iso_3166_2'    => $c['iso_3166_2'],
                'iso_3166_3'    => $c['iso_3166_3'],
                'name_en'       => $c['name_en'],
                'name_de'       => $c['name_de'],
                'region'        => $c['region'],
                'subregion'     => $c['subregion'],
                'currency_code' => $c['currency_code'],
                'phone_code'    => $c['phone_code'],
                'created_at'    => now(),
                'updated_at'    => now(),
            ]);
        }
    }
}
