tree -axpsh app > ".audits/tree/tree-app.txt"
tree -axpsh bootstrap > ".audits/tree/tree-bootstrap.txt"
tree -axpsh config > ".audits/tree/tree-config.txt"
tree -axpsh database > ".audits/tree/tree-database.txt"
tree -axLpsh 1 node_modules > ".audits/tree/tree-node_modules.txt"
tree -axpsh public > ".audits/tree/tree-public.txt"
# tree -axpsh --dirsfirst resources > ".audits/tree/tree-resources-full.txt"
tree -axpsh --dirsfirst resources -I "outline|solid" > ".audits/tree/tree-resources.txt"
tree -axpsh routes > ".audits/tree/tree-routes.txt"
tree -axpsh storage > ".audits/tree/tree-storage.txt"
tree -axpsh tests > ".audits/tree/tree-tests.txt"
tree -axLpsh 1 vendor > ".audits/tree/tree-vendor.txt"
tree -axLpsh 1 /home/gunreip/code/tafeld > ".audits/tree/tree-tafeld.txt"
